name: Deploy to Hosting
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Hosting
        uses: appleboy/ssh-action@master
        env:
          WORKDIR: "/home/${{secrets.PROJECT}}"
          GIT: "https://${{secrets.GH_USER}}:${{secrets.GH_TOKEN}}@github.com/${{secrets.GH_USER}}/${{secrets.PROJECT}}.git"
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            sudo rm -rf ${{env.WORKDIR}}
            sudo mkdir -p ${{env.WORKDIR}}
            cd ${{env.WORKDIR}}
            git clone ${{env.GIT}} .
            echo "${{secrets.ENV}}" | base64 -d > .env
            bash "cmd/hosting.sh"